### ISSUE TITLE
v1.11.0 test fails for "Application header is rendered"

### ISSUE THREAD

**Issue by resmall** [emberjs/starter-kit#66]
I cloned the repository and runned the test.

```
Application header is rendered
Expected:   
"Welcome to Ember.js"
Result:     
""
Diff:   
"Welcome to Ember.js" "" 
Source:     
    at http://ember.local/tests/tests.js:28:22
    at andThen (http://ember.local/js/libs/ember-1.11.0.js:37216:35)
    at http://ember.local/js/libs/ember-1.11.0.js:37943:25
    at isolate (http://ember.local/js/libs/ember-1.11.0.js:38137:15)
    at http://ember.local/js/libs/ember-1.11.0.js:38120:16
    at tryCatch (http://ember.local/js/libs/ember-1.11.0.js:50466:16)
    at invokeCallback (http://ember.local/js/libs/ember-1.11.0.js:50478:17)
```

I tried just opening the index.html file and also accessing it through server. No console errors shown.

**Comment by gitTerebi** [comment]
All tests fail actually.

This one to
